server {
    listen 80;
    server_name _;

    location /media/ {
        alias /usr/share/nginx/media/;
        autoindex off;
        expires 7d;
        add_header Cache-Control "public, immutable";
        add_header Access-Control-Allow-Origin "*";
    }

    location / {
        return 404;
    }
}
