#!/usr/bin/env python3
"""Add audit-pass keys to all 13 lalaka locale JSONs (additive only)."""
import json
from pathlib import Path

OUT = Path("/opt/skazka-bot/web/locales")

T = {
    # Server-side form error (when /create?err=1 redirects back)
    "create_err":         {"en":"Please fix the highlighted fields and try again.","de":"Bitte korrigieren Sie die markierten Felder.","es":"Por favor, corrige los campos marcados.","fr":"Merci de corriger les champs surlignés.","it":"Correggi i campi evidenziati.","pl":"Popraw zaznaczone pola.","pt-BR":"Por favor, corrija os campos destacados.","tr":"Lütfen vurgulanan alanları düzeltin.","ja":"ハイライトされた項目を修正してください。","ko":"강조된 필드를 수정해주세요.","ar":"يرجى تصحيح الحقول المُمَيَّزَة.","ru":"Исправьте выделенные поля.","uk":"Виправте підсвічені поля."},

    # Order page button-busy states
    "order_processing":   {"en":"Processing…","de":"Wird verarbeitet…","es":"Procesando…","fr":"Traitement…","it":"Elaborazione…","pl":"Przetwarzanie…","pt-BR":"Processando…","tr":"İşleniyor…","ja":"処理中…","ko":"처리 중…","ar":"جارٍ المعالجة…","ru":"Обработка…","uk":"Обробка…"},
    "order_photo_too_large": {"en":"Photo too large (max 10 MB)","de":"Foto zu groß (max. 10 MB)","es":"Foto demasiado grande (máx. 10 MB)","fr":"Photo trop volumineuse (max 10 Mo)","it":"Foto troppo grande (max 10 MB)","pl":"Zdjęcie zbyt duże (maks. 10 MB)","pt-BR":"Foto muito grande (máx. 10 MB)","tr":"Fotoğraf çok büyük (en fazla 10 MB)","ja":"写真が大きすぎます（最大10 MB）","ko":"사진이 너무 큽니다 (최대 10 MB)","ar":"الصورة كبيرة جدًا (الحد الأقصى ١٠ ميغابايت)","ru":"Фото слишком большое (максимум 10 МБ)","uk":"Фото завелике (максимум 10 МБ)"},

    # Rating widget on done state
    "order_rate_q":       {"en":"How was the story?","de":"Wie war die Geschichte?","es":"¿Qué te pareció el cuento?","fr":"Qu'avez-vous pensé de l'histoire ?","it":"Com'è stata la storia?","pl":"Jak ci się podobała bajka?","pt-BR":"Como foi o conto?","tr":"Masal nasıldı?","ja":"お話はいかがでしたか？","ko":"동화는 어땠나요?","ar":"كيف كانت القصة؟","ru":"Как вам сказка?","uk":"Як вам казка?"},
    "order_rate_loved":   {"en":"💜 Loved it","de":"💜 Toll","es":"💜 Encantó","fr":"💜 Adoré","it":"💜 Adorato","pl":"💜 Super","pt-BR":"💜 Amei","tr":"💜 Harikaydı","ja":"💜 大好き","ko":"💜 너무 좋아요","ar":"💜 رائعة","ru":"💜 Восторг","uk":"💜 Чудово"},
    "order_rate_ok":      {"en":"👌 OK","de":"👌 In Ordnung","es":"👌 Bien","fr":"👌 Bien","it":"👌 Bene","pl":"👌 Ok","pt-BR":"👌 Ok","tr":"👌 İdare eder","ja":"👌 まあまあ","ko":"👌 괜찮아요","ar":"👌 جيدة","ru":"👌 Нормально","uk":"👌 Нормально"},
    "order_rate_bad":     {"en":"😔 Not great","de":"😔 Nicht so","es":"😔 Regular","fr":"😔 Pas top","it":"😔 Così così","pl":"😔 Średnio","pt-BR":"😔 Nem tanto","tr":"😔 Pek değil","ja":"😔 いまいち","ko":"😔 별로예요","ar":"😔 ليست رائعة","ru":"😔 Не очень","uk":"😔 Не дуже"},
    "order_rate_thanks":  {"en":"Thanks for your feedback!","de":"Danke für Ihr Feedback!","es":"¡Gracias por tus comentarios!","fr":"Merci pour votre retour !","it":"Grazie per il tuo feedback!","pl":"Dziękujemy za opinię!","pt-BR":"Obrigado pelo seu feedback!","tr":"Geri bildiriminiz için teşekkürler!","ja":"フィードバックありがとうございます！","ko":"피드백 감사합니다!","ar":"شكرًا على ملاحظاتك!","ru":"Спасибо за оценку!","uk":"Дякуємо за відгук!"},

    # Demo player
    "demo_label":         {"en":"30-second sample","de":"30-Sekunden-Demo","es":"Demo de 30 segundos","fr":"Démo de 30 secondes","it":"Demo di 30 secondi","pl":"30-sekundowe demo","pt-BR":"Demo de 30 segundos","tr":"30 saniyelik demo","ja":"30秒のサンプル","ko":"30초 샘플","ar":"عيّنة ٣٠ ثانية","ru":"Демо 30 секунд","uk":"Демо 30 секунд"},
    "demo_caption":       {"en":"This is how a Lalaka story sounds — narrated in your language.","de":"So klingt eine Lalaka-Geschichte — erzählt in Ihrer Sprache.","es":"Así suena un cuento de Lalaka — narrado en tu idioma.","fr":"Voici comment sonne un conte Lalaka — narré dans votre langue.","it":"Ecco come suona una fiaba di Lalaka — narrata nella tua lingua.","pl":"Tak brzmi bajka Lalaka — opowiedziana w twoim języku.","pt-BR":"Assim soa um conto Lalaka — narrado em seu idioma.","tr":"Bir Lalaka masalı böyle anlatılır — kendi dilinizde.","ja":"Lalakaのお話はこんな感じです — あなたの言語で。","ko":"Lalaka 동화는 이렇게 들립니다 — 당신의 언어로 나레이션됩니다.","ar":"هكذا تبدو قصة Lalaka — تُسرَد بلغتك.","ru":"Так звучит сказка Lalaka — на вашем языке.","uk":"Так звучить казка Lalaka — вашою мовою."},

    # Preset topic chips (same as skazik chips, in 13 langs)
    "chip_dark":          {"en":"🌙 Afraid of the dark","de":"🌙 Hat Angst vor der Dunkelheit","es":"🌙 Le teme a la oscuridad","fr":"🌙 A peur du noir","it":"🌙 Ha paura del buio","pl":"🌙 Boi się ciemności","pt-BR":"🌙 Tem medo do escuro","tr":"🌙 Karanlıktan korkuyor","ja":"🌙 暗いのが怖い","ko":"🌙 어둠을 무서워해요","ar":"🌙 يخاف من الظلام","ru":"🌙 Боится темноты","uk":"🌙 Боїться темряви"},
    "chip_dark_full":     {"en":"A story about a 4-year-old child who is afraid of the dark and won't fall asleep alone. Let them find a magical helper and learn to deal with it.","de":"Eine Geschichte über ein 4-jähriges Kind, das Angst vor der Dunkelheit hat und nicht allein einschlafen will. Lass es einen magischen Helfer finden und lernen, damit umzugehen.","es":"Un cuento sobre un niño de 4 años que le teme a la oscuridad y no quiere dormir solo. Que encuentre un ayudante mágico y aprenda a manejarlo.","fr":"Une histoire sur un enfant de 4 ans qui a peur du noir et ne veut pas s'endormir seul. Qu'il trouve un aide magique et apprenne à gérer cela.","it":"Una storia su un bambino di 4 anni che ha paura del buio e non vuole dormire da solo. Che trovi un aiutante magico e impari a gestirlo.","pl":"Bajka o 4-letnim dziecku, które boi się ciemności i nie chce zasypiać samo. Niech znajdzie magicznego pomocnika i nauczy się z tym radzić.","pt-BR":"Um conto sobre uma criança de 4 anos que tem medo do escuro e não dorme sozinha. Que encontre um ajudante mágico e aprenda a lidar com isso.","tr":"4 yaşındaki, karanlıktan korkup tek başına uyumak istemeyen bir çocuğun masalı. Sihirli bir yardımcı bulup bununla baş etmeyi öğrensin.","ja":"暗いのが怖くて一人で眠れない4歳の子どもの物語。魔法の助けを見つけて、それに対処することを学びます。","ko":"어둠을 무서워해서 혼자 잠들지 못하는 4살 아이의 이야기. 마법의 도우미를 만나 극복하는 법을 배웁니다.","ar":"قصة عن طفل عمره ٤ سنوات يخاف من الظلام ولا يستطيع النوم وحده. ليجد مساعدًا سحريًا ويتعلم كيف يتغلب على ذلك.","ru":"Сказка про ребёнка 4 лет, который боится темноты и не хочет засыпать один. Пусть найдёт волшебного помощника и научится с этим справляться.","uk":"Казка про дитину 4 років, яка боїться темряви і не хоче засинати сама. Хай знайде чарівного помічника і навчиться з цим справлятися."},

    "chip_teeth":         {"en":"🦷 Won't brush teeth","de":"🦷 Will Zähne nicht putzen","es":"🦷 No quiere cepillarse","fr":"🦷 Ne veut pas se brosser les dents","it":"🦷 Non vuole lavarsi i denti","pl":"🦷 Nie chce myć zębów","pt-BR":"🦷 Não quer escovar os dentes","tr":"🦷 Diş fırçalamak istemiyor","ja":"🦷 歯磨きが嫌い","ko":"🦷 양치를 안 해요","ar":"🦷 لا يحب تنظيف أسنانه","ru":"🦷 Не любит чистить зубы","uk":"🦷 Не любить чистити зуби"},
    "chip_teeth_full":    {"en":"A story about a 5-year-old child who hates brushing teeth. Let a friendly tooth fairy show what happens to neglected teeth.","de":"Eine Geschichte über ein 5-jähriges Kind, das Zähneputzen hasst. Eine freundliche Zahnfee zeigt, was mit vernachlässigten Zähnen passiert.","es":"Un cuento sobre un niño de 5 años que odia cepillarse los dientes. Que un hada amable le muestre qué pasa con los dientes descuidados.","fr":"Une histoire sur un enfant de 5 ans qui déteste se brosser les dents. Une gentille fée des dents montre ce qui arrive aux dents négligées.","it":"Una storia su un bambino di 5 anni che odia lavarsi i denti. Una fatina dei denti gentile mostra cosa succede ai denti trascurati.","pl":"Bajka o 5-letnim dziecku, które nie znosi mycia zębów. Niech miła wróżka pokaże, co dzieje się z zaniedbanymi zębami.","pt-BR":"Um conto sobre uma criança de 5 anos que odeia escovar os dentes. Que uma simpática fada dos dentes mostre o que acontece com dentes descuidados.","tr":"5 yaşındaki, diş fırçalamaktan nefret eden bir çocuğun masalı. Sevimli bir diş perisi, ihmal edilen dişlere ne olacağını göstersin.","ja":"歯磨きが大嫌いな5歳の子どもの物語。優しい歯の妖精が、磨かない歯がどうなるか教えてくれます。","ko":"양치질을 싫어하는 5살 아이의 이야기. 친절한 이의 요정이 방치된 이가 어떻게 되는지 보여줍니다.","ar":"قصة عن طفل عمره ٥ سنوات يكره تنظيف أسنانه. تأتي جنية الأسنان اللطيفة لتُريه ماذا يحدث للأسنان المهملة.","ru":"Сказка про ребёнка 5 лет, который не любит чистить зубы. Пусть встретит волшебную фею, которая научит, что бывает с зубами без ухода.","uk":"Казка про дитину 5 років, яка не любить чистити зуби. Хай зустріне чарівну фею, яка покаже, що буває із зубами без догляду."},

    "chip_doctor":        {"en":"🏥 Afraid of doctors","de":"🏥 Hat Angst vor Ärzten","es":"🏥 Le teme al médico","fr":"🏥 A peur du médecin","it":"🏥 Ha paura del dottore","pl":"🏥 Boi się lekarza","pt-BR":"🏥 Tem medo do médico","tr":"🏥 Doktordan korkuyor","ja":"🏥 病院が怖い","ko":"🏥 병원을 무서워해요","ar":"🏥 يخاف من الطبيب","ru":"🏥 Боится врачей","uk":"🏥 Боїться лікарів"},
    "chip_doctor_full":   {"en":"A story about a 3-year-old child who is scared to visit the doctor. Let them befriend a kind animal-doctor and realize there's nothing to fear.","de":"Eine Geschichte über ein 3-jähriges Kind, das Angst hat, zum Arzt zu gehen. Lass es einen freundlichen Tierarzt kennenlernen und merken, dass es nichts zu fürchten gibt.","es":"Un cuento sobre un niño de 3 años que le teme al médico. Que se haga amigo de un doctor-animal amable y entienda que no hay nada que temer.","fr":"Une histoire sur un enfant de 3 ans qui a peur d'aller chez le médecin. Qu'il se lie d'amitié avec un gentil docteur-animal et réalise qu'il n'y a rien à craindre.","it":"Una storia su un bambino di 3 anni che ha paura di andare dal dottore. Diventi amico di un dottore-animale gentile e capisca che non c'è nulla da temere.","pl":"Bajka o 3-letnim dziecku, które boi się iść do lekarza. Niech zaprzyjaźni się z miłym doktorem-zwierzakiem i zrozumie, że nie ma się czego bać.","pt-BR":"Um conto sobre uma criança de 3 anos com medo de ir ao médico. Que faça amizade com um doutor-bichinho gentil e perceba que não há nada a temer.","tr":"3 yaşındaki, doktora gitmekten korkan bir çocuğun masalı. Sevecen bir hayvan-doktor ile dost olup korkacak bir şey olmadığını anlasın.","ja":"病院に行くのが怖い3歳の子どもの物語。優しい動物のお医者さんと友達になり、怖がる必要がないと気づきます。","ko":"병원 가는 것을 무서워하는 3살 아이의 이야기. 친절한 동물 의사 친구를 만나 두려워할 게 없다는 것을 깨닫습니다.","ar":"قصة عن طفل عمره ٣ سنوات يخاف من زيارة الطبيب. ليصادق طبيبًا حيوانًا لطيفًا ويدرك أنه لا داعي للخوف.","ru":"Сказка про ребёнка 3 лет, который боится идти к врачу. Пусть подружится с добрым доктором-зверем и поймёт, что бояться нечего.","uk":"Казка про дитину 3 років, яка боїться йти до лікаря. Хай подружиться з добрим лікарем-звіром і зрозуміє, що боятися нема чого."},

    "chip_garden":        {"en":"🎒 Starting kindergarten","de":"🎒 Geht in den Kindergarten","es":"🎒 Empieza la guardería","fr":"🎒 Commence la maternelle","it":"🎒 Inizia l'asilo","pl":"🎒 Idzie do przedszkola","pt-BR":"🎒 Vai para a creche","tr":"🎒 Anaokuluna başlıyor","ja":"🎒 幼稚園が始まる","ko":"🎒 어린이집에 가요","ar":"🎒 يبدأ روضة الأطفال","ru":"🎒 Идёт в детский сад","uk":"🎒 Іде в дитсадок"},
    "chip_garden_full":   {"en":"A story about a 4-year-old going to kindergarten for the first time and feeling anxious. Let them find kind friends and realize it can be fun.","de":"Eine Geschichte über ein 4-jähriges Kind, das zum ersten Mal in den Kindergarten geht und nervös ist. Lass es nette Freunde finden und merken, dass es Spaß macht.","es":"Un cuento sobre un niño de 4 años que va a la guardería por primera vez y está nervioso. Que haga amigos amables y descubra que es divertido.","fr":"Une histoire sur un enfant de 4 ans qui va à la maternelle pour la première fois et a peur. Qu'il se fasse des amis gentils et découvre que c'est amusant.","it":"Una storia su un bambino di 4 anni che va all'asilo per la prima volta ed è ansioso. Trovi amici gentili e scopra che è divertente.","pl":"Bajka o 4-latku, który po raz pierwszy idzie do przedszkola i jest niespokojny. Niech znajdzie miłych przyjaciół i odkryje, że to świetna zabawa.","pt-BR":"Um conto sobre uma criança de 4 anos indo à creche pela primeira vez e ansiosa. Que faça amigos legais e descubra que é divertido.","tr":"İlk kez anaokuluna giden, endişeli 4 yaşındaki bir çocuğun masalı. İyi arkadaşlar edinip orada eğlenceli olduğunu keşfetsin.","ja":"初めて幼稚園に行く4歳の子どもが不安に思う物語。優しい友達を見つけ、楽しいと気づきます。","ko":"처음 어린이집에 가는 4살 아이의 이야기. 친절한 친구를 만나 즐겁다는 것을 알게 됩니다.","ar":"قصة عن طفل عمره ٤ سنوات يذهب إلى الروضة لأول مرة ويشعر بالقلق. ليجد أصدقاء طيبين ويكتشف أن الأمر ممتع.","ru":"Сказка про ребёнка 4 лет, который первый раз идёт в детский сад и переживает. Пусть найдёт добрых друзей и поймёт, что в саду интересно.","uk":"Казка про дитину 4 років, яка вперше йде в дитсадок і хвилюється. Хай знайде добрих друзів і зрозуміє, що в садку цікаво."},

    "chip_swim":          {"en":"🏊 Learning to swim","de":"🏊 Lernt schwimmen","es":"🏊 Aprende a nadar","fr":"🏊 Apprend à nager","it":"🏊 Impara a nuotare","pl":"🏊 Uczy się pływać","pt-BR":"🏊 Aprendendo a nadar","tr":"🏊 Yüzme öğreniyor","ja":"🏊 水泳を覚える","ko":"🏊 수영을 배워요","ar":"🏊 يتعلم السباحة","ru":"🏊 Учится плавать","uk":"🏊 Вчиться плавати"},
    "chip_swim_full":     {"en":"A story about a 5-year-old learning to swim and a little afraid of water. Let them meet an underwater friend who shows water can be your friend.","de":"Eine Geschichte über ein 5-jähriges Kind, das schwimmen lernt und Angst vor Wasser hat. Lass es einen Unterwasserfreund treffen, der zeigt, dass Wasser ein Freund sein kann.","es":"Un cuento sobre un niño de 5 años que aprende a nadar y le teme un poco al agua. Que conozca a un amigo submarino que le enseñe que el agua puede ser amiga.","fr":"Une histoire sur un enfant de 5 ans qui apprend à nager et a un peu peur de l'eau. Qu'il rencontre un ami sous-marin qui lui montre que l'eau peut être amie.","it":"Una storia su un bambino di 5 anni che impara a nuotare e ha un po' paura dell'acqua. Incontri un amico sottomarino che gli mostri che l'acqua può essere amica.","pl":"Bajka o 5-latku, który uczy się pływać i trochę boi wody. Niech spotka podwodnego przyjaciela, który pokaże, że woda może być przyjacielem.","pt-BR":"Um conto sobre uma criança de 5 anos aprendendo a nadar e com um pouco de medo da água. Que encontre um amigo submarino que mostre que a água pode ser amiga.","tr":"5 yaşında, yüzmeyi öğrenen ve sudan biraz korkan bir çocuğun masalı. Su altı bir arkadaş tanıyıp suyun da dostluk olabileceğini keşfetsin.","ja":"水泳を習い始めた5歳の子どもが水を少し怖がる物語。海の友達と出会い、水が友達になれることを知ります。","ko":"수영을 배우는 5살 아이가 물을 조금 무서워하는 이야기. 바닷속 친구를 만나 물도 친구가 될 수 있다는 것을 알게 됩니다.","ar":"قصة عن طفل عمره ٥ سنوات يتعلم السباحة ويخاف قليلاً من الماء. ليلتقي بصديق تحت الماء يُريه أن الماء يمكن أن يكون صديقًا.","ru":"Сказка про ребёнка 5 лет, который учится плавать и пока боится воды. Пусть встретит подводного жителя, который научит дружить с водой.","uk":"Казка про дитину 5 років, яка вчиться плавати і поки боїться води. Хай зустріне підводного жителя, який навчить дружити з водою."},
}

LOCALES = ["en","de","es","fr","it","pl","pt-BR","tr","ja","ko","ar","ru","uk"]
for loc in LOCALES:
    p = OUT / f"{loc}.json"
    existing = json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}
    added = 0
    for key, tr in T.items():
        if key not in existing:
            added += 1
        existing[key] = tr.get(loc) or tr["en"]
    p.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  {loc}: {len(existing)} keys total (+{added} new)")
